### ISSUE TITLE
I think you forgot to publish to packgist ?

### ISSUE THREAD

**Issue by vermaysha** [CharrafiMed/global-search-modal#38]
Hi @CharrafiMed, I found a bug that should have been resolved, maybe you forgot to publish to packgist?
![image](https://github.com/user-attachments/assets/1d936ae5-da21-4aa9-9dc2-392a52591679)

**Comment by CharrafiMed** [comment]
hi! @vermaysha, you're right thanks.  I’ve just released a new [release](https://github.com/CharrafiMed/global-search-modal/releases/tag/v3.0.8)  let me know if the bug is resolved. If all works well, I’ll go ahead and close the issue.

**Comment by vermaysha** [comment]
> hi! @vermaysha, you're right thanks. I’ve just released a new [release](https://github.com/CharrafiMed/global-search-modal/releases/tag/v3.0.8) let me know if the bug is resolved. If all works well, I’ll go ahead and close the issue.

thanks
