### ISSUE TITLE
Global Search Result Details Formatting

### ISSUE THREAD

**Issue by NathanLochala** [CharrafiMed/global-search-modal#39]
When adding the function `getGlobalSearchResultDetails(Model $record)` to a resource, the resulting formatting when searching fails to justify to the left. Meaning, the text seems to have spaces add or is indented. It isn't fully justified to the left and inline with the title. There doesn't seem to be a pattern. I have a model that includes two Detail lines. 
- The employee's email
- The employee's job title

See below: Forgive the blurring, but the important part is seeing that each result returned isn't fully justified to the left. On the last search entry, the email isn't fully justified to the left, but the job title is. For the other results, the email is justified to the left, but the job title seems to have a random number of spaces added to the front of it. 
![image](https://github.com/user-attachments/assets/f39ac981-9187-4e94-9bcf-8688d88a0abe)

Here is another sanitized view. As you see, it doesn't seem to be padded with spaces or anything, however, clearly it is not justified to the left like I would expect the details (email and job title) to be:
![image](https://github.com/user-attachments/assets/07a5c1da-adf2-4163-98b6-70f0241e61b0)

Here is my resource global search results methods:
```php
class EmployeeResource extends Resource
{
    protected static ?string $model = Employee::class;
    protected static ?string $navigationGroup = 'Personnel';
    protected static ?string $navigationIcon = 'heroicon-c-user-group';

    /*###############################################################
    # GLOBAL SEARCH SETTINGS
    ###############################################################*/
    public static function getGloballySearchableAttributes(): array
    {
        return ['full_legal_name', 'email'];
    }

    public static function getGlobalSearchResultTitle(Model $record): string|Htmlable
    {
        return $record->full_name;
    }

    public static function getGlobalSearchResultDetails(Model $record): array
    {
        return [
            $record->email,
            optional($record->location)->name.' - '.$record->job_title,
        ];
    }

    public static function getGlobalSearchResultUrl(Model $record): string
    {
        return EmployeeResource::getUrl('view', ['record' => $record]);
    }
```

**Comment by CharrafiMed** [comment]
Thanks for bringing this up! I understand your concern. In my plugin, I initially copied the search details directly from Filament's implementation to maintain consistency with their design. Here's the snippet I based it on:
![image](https://github.com/user-attachments/assets/1fe8025d-71f8-41b6-bd01-6180f02dffc3) 
That being said, I agree that this could be improved for a better UI experience. I’ll work on updating the interface to make it more polished and user-friendly.

Before I get started, could you share how you'd like it to look? I'd to consider your preferences.

**Comment by NathanLochala** [comment]
I would like to see the `$title` and the `$value` to lineup on the left. 
For example, this is how it currently is:
![image](https://github.com/user-attachments/assets/ee8bb32e-3001-47a0-947c-7d9fe6cec776)

This is how I would like it to look: 
![Xnip2024-09-16_12-56-45](https://github.com/user-attachments/assets/7090663b-99e7-4e14-85ba-3986812d03bb)

If you look at the email address. In the first picture, the email address seems to have several spaces added to the front. In the second picture, the email address and the title are directly inline with each other. That is how I would expect it to work.
