### ISSUE TITLE
Expand the url target

### ISSUE THREAD

**Issue by NathanLochala** [CharrafiMed/global-search-modal#41]
First, @CharrafiMed I'm super impressed with your responsiveness. I had the issues yesterday and you pushed a fix same day. I didn't expect that, by any means, but am grateful for the quick fix. This suggestion doesn't require a quick fix. However, I think it could be very helpful. 

Current, you can only click on the text of the search result to go to that item. However, it would be great if I could click anywhere on the search result and it take me to the item. For instance, in the below picture, the href is inside the `<li>` and doesn't include the area in the red circle:
<img width="800" alt="image" src="https://github.com/user-attachments/assets/c7075874-596f-4c3f-a127-20455e4f9348">

However, it would be best if the whole section is clickable, like below: 
<img width="744" alt="image" src="https://github.com/user-attachments/assets/a7dab7f5-7258-48f5-8d9c-7f20a4e2fcc5">

**Comment by CharrafiMed** [comment]
Hey @NathanLochala!

Thank you! I'm really glad the quick fix worked for you.

Your suggestion about making the entire search result clickable is an excellent idea, and I can see how it would improve the user experience. I'll be looking into implementing this, as it could benefit the community.

For this feature, I plan to make it configurable like other features and have it controlled from the PHP plugin class. That way, developers can easily toggle this behavior based on their needs.

Also, I want to encourage you to keep the suggestions coming! Don’t hesitate to open new issues or feature requests—your input is valuable and helps make the project better for everyone. Even small ideas can lead to big improvements, so don’t be shy!

I'll keep this issue open and will provide updates as I explore the implementation. Thanks again for your continued contributions!

**Comment by NathanLochala** [comment]
Thank you, brother! I appreciate the feedback. I like the idea of making it configurable. I'll let you know if I think of anything else.
