### ISSUE TITLE
RTL Direction support

### ISSUE THREAD

**Issue by imami** [CharrafiMed/global-search-modal#42]
As you can see in the image bellow, there are some issues in the UI while the Filamentphp's locale is set to an RTL language.

<img width="692" alt="image" src="https://github.com/user-attachments/assets/b6f52f8b-5ff6-4e19-b8bf-dd908a88390b">

- The lines before the list items are still in the LTR style
- Paddings/Margins/Alignment of the footer text and it's icons.

**Comment by CharrafiMed** [comment]
hey @imami 
Thank you for opening a separate issue and providing a clear description. 
I'll prioritize adding RTL language support to accommodate Arabic, Persian, and similar languages.
