### ISSUE TITLE
hover style not removed with keyboard keys

### ISSUE THREAD

**Issue by leobury** [CharrafiMed/global-search-modal#43]
Hey ! 

Thanks for your work ! 

I've found a strange behaviour. When you use the shortcut arrows, the hover style remains from the moment you move over a result.

See the attached video:
https://github.com/user-attachments/assets/a234aeb0-27df-43d4-b07e-ea066a641a9c

**Comment by CharrafiMed** [comment]
hey @leobury  

thanks for catching this bug, I'll fix it soon
