### ISSUE TITLE
Exception when search begins with space...

### ISSUE THREAD

**Issue by NathanLochala** [CharrafiMed/global-search-modal#52]
Hey brother, 
I noticed the following behavior. 
1. Click the search field to open the global search modal window.
2. Hit the space bar and then wait a second.
3. This executes the search on an empty string.
Thus, we get a whole lot of exceptions returned. Seems to be that it is attempting to execute the query on a null string.
It would be great if there were some protection against that. Perhaps a regex or `trim()` before executing a query with it. 

![image](https://github.com/user-attachments/assets/862a80c4-8514-44bc-8211-2d2ea9bf7338)

**Comment by CharrafiMed** [comment]
hey bro

Thanks for pointing that out! I noticed the critique and, even though I’m short on time, I’m going to fix it right away.
