### ISSUE TITLE
Modal not loading, timeout during checking for node solves it.

### ISSUE THREAD

**Issue by derpoho** [CharrafiMed/global-search-modal#59]
We have the case, that the events are not attached to the search field, after debugging we found that at the time observer.js is initialized the search node is not yet there. if we wrap this (https://github.com/CharrafiMed/global-search-modal/blob/master/resources/js/observer.js#L6) in a setTimeout with 200 ms delay all works fine. Not sure why we are the only ones experiencing this, we have a simple Filament Setup with no extras besides the Minimal Theme.

Can you maybe add this small delay? or make it optional?

**Comment by CharrafiMed** [comment]
this plugin requires filament version v3.2.93 or later are you using an older version?

**Comment by derpoho** [comment]
works now. sorry!
didn't see the dependency.
