### ISSUE TITLE
HtmlString and Blade::render() not working

### ISSUE THREAD

**Issue by serban-anghel** [CharrafiMed/global-search-modal#73]
Hi, I've encountered some issues in displaying HtmlString and Blade::render().
In the search results I show the resource name and the status (from an enum list), I use a filament badge component to style the status and HtmlString with Blade::render() to show it. 
This is the code https://i.imgur.com/4ZoDJGA.png
In the default global search from filament it looks like this https://i.imgur.com/WLSSMCf.png I don't have any issues. 

In the global search modal plugin the filament badge doesn't show and it displays the html as text https://i.imgur.com/RiwAw0v.png and the recent and favorite items don't have a title, just [object Object] https://i.imgur.com/k1viRvv.png

Thank you.

**Comment by CharrafiMed** [comment]
hey @serban-anghel,  what if you use raw HTML  to style the search items? i believe you can do that with the plugin

**Comment by serban-anghel** [comment]
it works with raw HTML, thank you
