### ISSUE TITLE
Multitenant broken

### ISSUE THREAD

**Issue by galliroberto** [CharrafiMed/global-search-modal#76]
During login Global search doesn't have Tenant.

Please add the
```
if (!Filament::getTenant()) {
    return null;
}
```
to src/Livewire/GlobalSearchModal.php

![image](https://github.com/user-attachments/assets/bfdea999-073b-4a01-897f-fc4097d97ea7)

**Comment by CharrafiMed** [comment]
hey @galliroberto !
thanks
